global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-backend'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080']

  - job_name: 'python-data-service'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['data-service:8000']
