CREATE TABLE assets (
    symbol VARCHAR(20) NOT NULL,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(20) NOT NULL,
    PRIMARY KEY (symbol)
);

CREATE TABLE price_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id VARCHAR(20) NOT NULL,
    open_price NUMERIC(19, 4) NOT NULL,
    close_price NUMERIC(19, 4) NOT NULL,
    high_price NUMERIC(19, 4) NOT NULL,
    low_price NUMERIC(19, 4) NOT NULL,
    volume NUMERIC(19, 4) NOT NULL,
    price_timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_asset_timestamp UNIQUE (asset_id, price_timestamp)
);

CREATE TABLE financial_statements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol VARCHAR(20) NOT NULL,
    fiscal_year INTEGER NOT NULL,
    period VARCHAR(10) NOT NULL,
    revenue NUMERIC(26, 4) NOT NULL,
    net_income NUMERIC(26, 4) NOT NULL,
    total_assets NUMERIC(26, 4) NOT NULL,
    total_liabilities NUMERIC(26, 4) NOT NULL,
    operating_cash_flow NUMERIC(26, 4) NOT NULL,
    CONSTRAINT uk_statement_symbol_year_period UNIQUE (symbol, fiscal_year, period)
);
