CREATE TABLE agent_analysis_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker          VARCHAR(32)  NOT NULL,
    decision        VARCHAR(16)  NOT NULL,
    confidence      INTEGER      NOT NULL,
    analysis_json   TEXT         NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_agent_analysis_history_ticker_created
    ON agent_analysis_history (ticker, created_at DESC);
