CREATE TABLE IF NOT EXISTS portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id VARCHAR(64) NOT NULL DEFAULT 'default',
    name VARCHAR(128) NOT NULL,
    base_currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    description VARCHAR(500),
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_portfolio_user_name UNIQUE (user_id, name)
);

CREATE TABLE IF NOT EXISTS portfolio_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    user_id VARCHAR(64) NOT NULL DEFAULT 'default',
    symbol VARCHAR(32),
    asset_type VARCHAR(32) NOT NULL,
    action VARCHAR(32) NOT NULL,
    quantity NUMERIC(24, 8) NOT NULL DEFAULT 0,
    price NUMERIC(24, 8) NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    fee NUMERIC(24, 8) NOT NULL DEFAULT 0,
    fx_rate_to_base NUMERIC(24, 10) NOT NULL DEFAULT 1,
    trade_date DATE NOT NULL,
    source VARCHAR(16) NOT NULL DEFAULT 'MANUAL',
    notes VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_portfolio_transactions_portfolio FOREIGN KEY (portfolio_id) REFERENCES portfolios(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_portfolio_transactions_portfolio_date
    ON portfolio_transactions(portfolio_id, trade_date, id);

CREATE INDEX IF NOT EXISTS idx_portfolio_transactions_user_symbol
    ON portfolio_transactions(user_id, symbol);

ALTER TABLE IF EXISTS journal_trades
    ADD COLUMN IF NOT EXISTS portfolio_id BIGINT;

ALTER TABLE IF EXISTS journal_trades
    ADD COLUMN IF NOT EXISTS transaction_id BIGINT;

CREATE INDEX IF NOT EXISTS idx_journal_trades_portfolio_id
    ON journal_trades(portfolio_id);

CREATE INDEX IF NOT EXISTS idx_journal_trades_transaction_id
    ON journal_trades(transaction_id);
