ALTER TABLE assets
    ADD COLUMN IF NOT EXISTS exchange VARCHAR(40),
    ADD COLUMN IF NOT EXISTS currency VARCHAR(10),
    ADD COLUMN IF NOT EXISTS provider VARCHAR(40),
    ADD COLUMN IF NOT EXISTS provider_symbol VARCHAR(40),
    ADD COLUMN IF NOT EXISTS metadata_status VARCHAR(20) NOT NULL DEFAULT 'UNAVAILABLE';

CREATE TABLE IF NOT EXISTS symbol_mapping (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    canonical_symbol VARCHAR(40) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    provider_symbol VARCHAR(80) NOT NULL,
    display_name VARCHAR(255),
    asset_type VARCHAR(20) NOT NULL,
    exchange VARCHAR(40),
    currency VARCHAR(10),
    priority INTEGER NOT NULL DEFAULT 100,
    status VARCHAR(30) NOT NULL,
    last_failure_reason VARCHAR(500),
    last_resolved_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_symbol_mapping_provider UNIQUE (canonical_symbol, provider, provider_symbol)
);

CREATE INDEX IF NOT EXISTS ix_symbol_mapping_lookup
    ON symbol_mapping (canonical_symbol, provider, status, priority);

INSERT INTO symbol_mapping (
    canonical_symbol,
    provider,
    provider_symbol,
    display_name,
    asset_type,
    exchange,
    currency,
    priority,
    status,
    last_resolved_at
)
VALUES (
    'DRAM',
    'YAHOO',
    'DRAM',
    'Roundhill Memory ETF',
    'ETF',
    'NYSEARCA',
    'USD',
    1,
    'MANUAL_OVERRIDE',
    CURRENT_TIMESTAMP
)
ON CONFLICT (canonical_symbol, provider, provider_symbol) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    asset_type = EXCLUDED.asset_type,
    exchange = EXCLUDED.exchange,
    currency = EXCLUDED.currency,
    priority = EXCLUDED.priority,
    status = EXCLUDED.status,
    last_resolved_at = EXCLUDED.last_resolved_at;
