package com.ozkaslibasar.financeproject.adapter.outbound.persistence.mapper;

import com.ozkaslibasar.financeproject.adapter.outbound.persistence.entity.PriceEntity;
import com.ozkaslibasar.financeproject.domain.model.PriceHistory;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

/**
 * MapStruct mapper for converting between {@link PriceHistory} and {@link PriceEntity}.
 */
@Mapper(componentModel = "spring")
public interface PricePersistenceMapper {

    @Mapping(target = "id", ignore = true) // Generated by DB
    PriceEntity toEntity(PriceHistory domain);

    PriceHistory toDomain(PriceEntity entity);

    List<PriceEntity> toEntityList(List<PriceHistory> domains);

    List<PriceHistory> toDomainList(List<PriceEntity> entities);
}
