package com.ozkaslibasar.financeproject.adapter.outbound.persistence.mapper;

import com.ozkaslibasar.financeproject.adapter.outbound.persistence.entity.PriceEntity;
import com.ozkaslibasar.financeproject.domain.model.PriceHistory;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.util.List;

/**
 * MapStruct mapper for converting between {@link PriceHistory} and {@link PriceEntity}.
 */
@Mapper(componentModel = "spring")
public interface PricePersistenceMapper {

    @Mapping(target = "id", ignore = true) // Generated by DB
    @Mapping(target = "assetId", source = "symbol")
    PriceEntity toEntity(PriceHistory domain);

    @Mapping(target = "symbol", source = "assetId")
    PriceHistory toDomain(PriceEntity entity);

    List<PriceEntity> toEntityList(List<PriceHistory> domains);

    List<PriceHistory> toDomainList(List<PriceEntity> entities);

    default Instant map(LocalDateTime value) {
        return value == null ? null : value.toInstant(ZoneOffset.UTC);
    }

    default LocalDateTime map(Instant value) {
        return value == null ? null : LocalDateTime.ofInstant(value, ZoneOffset.UTC);
    }
}
